-- Migration: index oci_blobs.storage_key for the OCI cleanup sweep's
-- pre-delete liveness re-check (#3085).
--
-- The sweep re-asserts blob liveness immediately before each destructive
-- storage delete. That predicate contains
-- `NOT EXISTS (SELECT 1 FROM oci_blobs b WHERE b.storage_key = k.storage_key)`.
--
-- Before #3085 that subquery ran once per batch, inside the candidate SELECT,
-- so a sequential scan was amortised across the whole batch. The re-check runs
-- it once per candidate, and oci_blobs has no index on storage_key -- migration
-- 118 indexed oci_upload_sessions.storage_temp_key and oci_upload_parts
-- .storage_key, but not this one, because nothing needed it per-row until now.
--
-- Measured on 300k blobs: 87 ms per hold without the index versus 0.19 ms with
-- it; a full 1000-row batch (OCI_UPLOAD_CLEANUP_KEY_SCAN_LIMIT) went from
-- 30.7 s to 0.19 s, ~163x. The cost scales linearly with registry size, so on a
-- large registry a batch would begin to approach the 15 minute claim TTL and
-- leases would lapse mid-sweep.
--
-- LOCK BEHAVIOUR. CREATE INDEX CONCURRENTLY is intentionally not used here,
-- matching migration 166: sqlx::migrate runs each migration file inside a
-- transaction, and CONCURRENTLY is rejected inside a transaction block.
--
-- A plain CREATE INDEX takes a SHARE lock on `oci_blobs` for the duration of
-- the build. SHARE conflicts with ROW EXCLUSIVE, so for as long as the build
-- runs:
--
--   * writes to oci_blobs BLOCK -- INSERT/UPDATE/DELETE, which means blob
--     commits on the push path wait, as do blob GC's row deletes;
--   * reads do NOT block -- plain SELECT takes ACCESS SHARE, which is
--     compatible with SHARE, so pulls and manifest resolution are unaffected.
--
-- (It is not ACCESS EXCLUSIVE. Nothing here rewrites the table or takes the
-- table fully offline; an earlier revision of this comment said otherwise and
-- was wrong. Plan the window against blocked writers, not blocked readers.)
--
-- This is a single-column btree on a table far smaller than `artifacts` (one
-- row per stored blob, deduplicated by (repository_id, digest)), so the build
-- is short -- but the write stall is real, and on a large registry the upgrade
-- should be scheduled accordingly.
--
-- Operators who cannot accept even that write stall should build the index out
-- of band, BEFORE deploying this migration, against a live table:
--
--   CREATE INDEX CONCURRENTLY idx_oci_blobs_storage_key ON oci_blobs (storage_key);
--
-- The IF NOT EXISTS below then makes this migration a no-op. Note that this is
-- the only supported way to avoid the stall: the migration itself cannot simply
-- be skipped, since sqlx tracks applied migrations by checksum and a missing
-- entry blocks the ledger.
--
-- DO build it, one way or the other. Correctness does not depend on the index
-- -- without it the liveness re-check still returns the right answer, just via
-- a sequential scan -- but forward progress does. Per the measurement above, on
-- a large registry the un-indexed re-check pushes a batch toward the 15 minute
-- claim TTL, and a sweep whose leases lapse mid-batch stops reclaiming storage.
-- Skipping the index outright is not an equivalent option; it trades a bounded
-- write stall for an unbounded GC stall.
CREATE INDEX IF NOT EXISTS idx_oci_blobs_storage_key
    ON oci_blobs (storage_key);
